### ISSUE TITLE
Help me to figure out how to use two CeleX5 sensors to record stereo datasets please.

### ISSUE THREAD

**Issue by aobi12138** [LarryDong/CeleX5_source#1]
I have two CeleX5 sensors and I want to record my stereo datasets. But I am facing with a difficult problem that I am not able to open the two sensors at the same time. When I open one of them, the other could not be opened. The following picture shows the error when I try opening the other CeleX5 sensor. Could anybody give some advice please?
![图片](https://user-images.githubusercontent.com/28434475/111771672-ed4c7a80-88e6-11eb-8791-079ed7de8ab8.png)

**Comment by LarryDong** [comment]
Hi, I've never used two sensors together. I have no ideas about this issue. Please tell us how to solve it if you have any clues. Thanks.

**Comment by aobi12138** [comment]
> Hi, I've never used two sensors together. I have no ideas about this issue. Please tell us how to solve it if you have any clues. Thanks.
Hi, I`ve solved this. The developers of CeleX5 uploaded source code and demo to Github. You can download the project by the follow url.
https://github.com/CelePixel/CeleX5-MIPI-Stereo

**Comment by LarryDong** [comment]
Cool
