### ISSUE TITLE
Miss  dir of Samples/Samples/lib/LInux

### ISSUE THREAD

**Issue by lizhihao6** [LarryDong/CeleX5_source#3]
according to CMakeList.txt 
```cmake
link_directories(${CeleX}/lib/Linux/x64)
```
there should be a dir of LInux

**Comment by LarryDong** [comment]
Yep, you need change the lib directory in CMakeLists.txt to your `libCeleX.so`.  
And you probably also need to re-compile the source code to generate `libCeleX.so`  due to the dependency of OpenCV.
